version: "3"
services:
  postgres:
    image: postgres:10.9-alpine
    environment:
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
volumes:
  pg_data: